name: Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout
            uses: actions/checkout@v4
        
        - name: Debug repository
            run: |
            echo "Current directory:"
            pwd
        
            echo "GitHub workspace:"
            echo "$GITHUB_WORKSPACE"
        
            echo "Root contents:"
            ls -la
        
            echo "Dockerfiles:"
            find . -iname "Dockerfile" -print