name: Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with: 
            client-id: ${{ dad634ce-f306-4854-a152-5fae6b7b00db }} 
            tenant-id: ${{ e3c039ae-24c0-4f09-bd5c-d6f37ba60f1f }} 
            subscription-id: ${{ 810b70f8-b651-46d2-b518-f99ed6fa5d56 }}

      - name: Login to ACR
        run: az acr login --name RAGApi --expose-token

      - name: Build Docker Image
        run: |
          docker build \
            -t RAGApi.azurecr.io/ragapi:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push \
            RAGApi.azurecr.io/ragapi:${{ github.sha }}
